name: Feature Branch Down

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14.x']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and Feature Branch Down
        run: |
          npm i
          npm run build
          npm run feature-branch-down
        env:
          CI: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DATABASE_URL: ${{ secrets.AWS_DATABASE_URL }}
          AWS_DEFAULT_REGION: 'us-west-1'
          GITHUB_BRANCH_NAME: ${{ github.head_ref }}
